### ISSUE TITLE
Vault prometheus-metrics token exposure

### ISSUE THREAD

**Issue by jjtroberts** [GoogleCloudPlatform/ops-agent#1035]
**Describe the bug**
The [ops-agent-engine prints its config.yaml](https://github.com/GoogleCloudPlatform/ops-agent/blob/47d43ec9bc7e1dd10a673a169940b089d2e00f23/cmd/google_cloud_ops_agent_engine/main.go#L51) which, when [configured with a vault token](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/third-party/vault#example-config), exposes the token in cloud logging.

**To Reproduce**
1. Start a GCE VM with image 'debian-11'
2. Install Ops Agent version '2.24.0' following instructions [here](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/installation#install-latest-version)
3. Customize the agent with configuration from [example here](https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/third-party/vault#example-config) and restart the agent
4. See error (redacted)
```
google_cloud_ops_agent_engine[4509]: 2023/01/10 19:32:16 Built-in config:
...
google_cloud_ops_agent_engine[4476]:       token: xxxxxxxxxxxxxxxxx”
```

**Expected behavior**
I expect the token to be redacted, or documentation updated to note how to avoid logging the secrets used in the config.yaml.

**Environment (please complete the following information):**
 - Project ID dev-octo-origin
 - VM ID 5802857856404292122
 - VM distro / OS: Debian
 - Ops Agent version 2.24.0
 - Ops Agent configuration
 
Terraform template_file as part of an instance group template startup script:
```
tee /etc/google-cloud-ops-agent/config.yaml > /dev/null << EOF
metrics:
  receivers:
    vault:
      type: vault
      insecure_skip_verify: true
      token: $VAULT_TOKEN
      endpoint: 127.0.0.1:8200
  service:
    pipelines:
      vault:
        receivers:
          - vault
logging:
  receivers:
    vault_audit:
      type: vault_audit
      include_paths: [/var/log/vault/audit.log]
  service:
    pipelines:
      vault:
        receivers:
          - vault_audit
EOF
```

**Comment by jefferbrecht** [comment]
Thanks for raising this; this is definitely something we will try to address for the next release.

Until that release is ready, you can use `exclude_logs` as a workaround to filter token logs (and any other logs with sensitive information by adding filters to `match_any` as appropriate) with this configuration:

```yaml
logging:
  processors:
    exclude_token:
      type: exclude_logs
      match_any:
      - jsonPayload.message =~ ".*ops-agent.*token:.*"
  service:
    pipelines:
      default_pipeline:
        receivers: [ syslog ]
        processors: [ exclude_token ]
```
