### ISSUE TITLE
JMX port for JVM monitoring will stay up if JMX port goes down on an VM

### ISSUE THREAD

**Issue by kaio-ru** [GoogleCloudPlatform/ops-agent#1181]
I have few VM's in Compute Engine that are running Java applications on RHEL 8. I am able to monitor them over JMX and I would like to set up an alarm that when one of those processes dies, Google Monitoring would send out an alarm, that JMX port is down.

I have set up a policy for workload.googleapis.com/jvm.threads.count for it. When I kill one of the processes, the opentelemetry-collector will hang like the JMX port is still up. There is a process java `-Dorg.slf4j.simpleLogger.defaultLogLevel=info io.opentelemetry.contrib.jmxmetrics.JmxMetrics -config /tmp/jmx-config-2646817184.properties` up and this seems to be feeding GCP this data. When I restart the google-cloud-ops-agent-opentelemetry-collector service on the server, the jvm.threads.count will drop and an alarm is being sent out

JMX config in yaml:

```
metrics:
  receivers:
    jvm:
      type: jvm
      endpoint: localhost:8565
      collection_interval: 60s
  service:
    pipelines:
      jvm:
        receivers:
          - jvm
```

Am I missing something or is this the expected behaviour currently?
