### ISSUE TITLE
Prometheus Config Generation Can Build Invalid Config Due To Inability To Skip Specific GCE Metadata Tags

### ISSUE THREAD

**Issue by ryanohnemus** [GoogleCloudPlatform/ops-agent#1517]
In some cases the gce metadata may have info that is completely unnecessary/unhelpful as a metric label and should not be included. Specifically when you have `metadata_startup_script` set to a long script that is included as a huge label in the generated scrape config. This can cause you to run into an almost identical issue as https://github.com/GoogleCloudPlatform/ops-agent/issues/1221 where parts of that startup script are attempted to be interpreted leading to the otel agent unable to start the metrics portion of the service.

Can `metadata_startup_script` (`startup_script`) always be excluded from https://github.com/GoogleCloudPlatform/ops-agent/blob/master/confgenerator/prometheus.go#L170-L173 or can there be a config option available to disable it from being included and potentially causing the otel agent to exit due to a bad config?

**Comment by quentinmit** [comment]
@ryanohnemus Do you have an example of a startup script that causes a broken configuration?

Our metadata labels mirror upstream Prometheus's GCE service discovery, and it looks like they don't do any special handling for the startup script: https://github.com/prometheus/prometheus/blob/cf528bef034dcf078d3bff0d50224a13068c391e/discovery/gce/gce.go#L195-L205

**Comment by ryanohnemus** [comment]
@quentinmit thank you for the quick reply! 

I am unable to share the entire script, but the part that breaks looks like this: 

```
#Variables
LOGFILE=${LOGDIR:-/tmp}/something.out
```

this results in the following exit: 
```
otelopscol[960219]: Error: failed to get config: cannot resolve the configuration: scheme "LOGDIR" is not supported for uri "LOGDIR:-/tmp"
```

The `config.yaml` we use to configure opsagent doesn't contain any of the LOGDIR info it comes directly out of the `startup-script` GCE Custom metadata field and the https://github.com/GoogleCloudPlatform/ops-agent/blob/master/confgenerator/prometheus.go#L170-L173  lines don't filter out that specific metadata key, resulting in a pretty large (full script) prometheus label being created in the generated `/run/google-cloud-ops-agent-opentelemetry-collector/otel.yaml` file. 

(Also I forgot to mention we are ops-agent version 2.42.0, which is 1 version from the latest). 

Let me know if i can provide any more details!

**Comment by igorpeshansky** [comment]
@ryanohnemus Would you be able to share your `config.yml`? That plus [your previous comment](https://github.com/GoogleCloudPlatform/ops-agent/issues/1517#issuecomment-1813255617) should give us enough info to reproduce this.

**Comment by ryanohnemus** [comment]
@igorpeshansky here is what I am using in the metrics section of the config.yml

```
metrics:
  receivers:
    metrics_endpoint:
      type: prometheus
      config:
        scrape_configs:
          - job_name: 'metrics_endpoint'
            static_configs:
              - targets: ['localhost:9090']
            scrape_interval: 10s
  service:
    pipelines:
      prometheus_pipeline:
        receivers: [metrics_endpoint]
  ```
