### ISSUE TITLE
Ops Agent fails intermittently to execute type modify_fields instruction

### ISSUE THREAD

**Issue by PawelKGalka** [GoogleCloudPlatform/ops-agent#1699]
**Describe the bug**
Havin exemplary field in `jsonPayload.auditLog.rawData.txTimeMillis` it is not always parsed to integer in Logs Explorer and remains as string

**To Reproduce**
1. Start a GCE VM with image RHEL 8
2. Install Ops Agent version 2.46.1
3. Customize the agent with configuration 
```yaml
logging:
  receivers:
    messages:
      type: files
      include_paths:
      - /var/log/messages
    secure:
      type: files
      include_paths:
      - /var/log/secure
    applogs_tcp:
      type: tcp
      format: json
      listen_port: 5160
  processors:
    parse:
      type: parse_json
      time_key: jsonPayload.timestamp
      time_format: "%Y-%m-%dT%H:%M:%S.%L%Z"
    adjust_fields_to_stackdriver:
      type: modify_fields
      fields:
        jsonPayload.auditLog.rawData.txTimeMillis:
          type: integer
  service:
    pipelines:
      default_pipeline:
        receivers: [messages, secure]
      applogs_pipeline:
        receivers: [applogs_tcp]
        processors: [parse, adjust_fields_to_stackdriver]
``` 
and restart the agent
5. See some values are still in String format
![image](https://github.com/GoogleCloudPlatform/ops-agent/assets/87987508/47f9c908-2da8-44c8-a7d2-8b078c7a06cc)

**Expected behavior**
Value is in integer format always

**Environment (please complete the following information):**
 - Project ID - can send via email
 - VM ID - can send via email
 - VM distro / OS: RHEL8
 - Ops Agent version 2.46.1
 - Ops Agent configuration
 - Ops Agent log

**Additional context**
NA
