### ISSUE TITLE
Add an option to systemd_journald receiver to filter by service

### ISSUE THREAD

**Issue by dcfreire** [GoogleCloudPlatform/ops-agent#1784]
It'd be very useful for my use case to be able to the configure `systemd_journald` receiver to only fetch logs from an specific service. Fluent Bit seems to have this [implemented](https://docs.fluentbit.io/manual/pipeline/inputs/systemd), so my guess is that this would only be a matter of exposing Systemd_Filter to the user. Something like:

```
  receivers:
    systemd_logs:
      type: systemd_journald
      systemd_filter:_SYSTEMD_UNIT=name.service
```

**Comment by jefferbrecht** [comment]
Hi @dcfreire, thanks for the feature request -- this sounds very reasonable. We'll open a tracker internally for it and I'll keep this issue updated once it's prioritized.

As a workaround, are you able to use `exclude_logs` to filter out anything that's not from `name.service`? Something like this, unfortunately it's a bit more obtuse:

```yaml
  receivers:
    systemd_logs:
      type: systemd_journald
  processors:
    name_service_only:
      type: exclude_logs
      match_any:
      - jsonPayload._SYSTEMD_UNIT != "name.service"
  service:
    pipelines:
      systemd:
        receivers:
        - systemd_logs
        processors:
        - name_service_only
```
