### ISSUE TITLE
collect_jvm_metrics is advertised but doesn't work with ActiveMQ integration

### ISSUE THREAD

**Issue by ViliusS** [GoogleCloudPlatform/ops-agent#1856]
**Describe the bug**
Ops Agent advertises "collect_jvm_metrics" parameter in the logs and it allows to set it, however parameter doesn't do anything.

**To Reproduce**
1. Start a GCE VM with image 'rocky-linux-9-v20240515'
2. Install Ops Agent version 'google-cloud-ops-agent-2.52.0-1.el9.x86_64.rpm'
3. Customize the agent with configuration and restart the agent
```
metrics:
  receivers:
    activemq:
      type: activemq
      endpoint: localhost:1099
      collection_interval: 15s
      collect_jvm_metrics: true
      username: admin
      password: admin
  service:
    pipelines:
      activemq:
        receivers:
          - activemq

```
4. See Cloud Monitoring that no JVM metrics are collected.
5. Now change configuration to and restart the agent
```
metrics:
  receivers:
    jvm:
      type: jvm
      endpoint: localhost:1099
      collection_interval: 15s
      username: admin
      password: admin
  service:
    pipelines:
      jvm:
        receivers:
          - jvm
```
6. This now collects JVM metrics.

**Expected behavior**
ActiveMQ application integration should be able to collect JVM metrics or collect_jvm_metrics parameter advertisement should be removed.
