### ISSUE TITLE
ActiveMQ integration doesn't work with ActiveMQ Artemis

### ISSUE THREAD

**Issue by ViliusS** [GoogleCloudPlatform/ops-agent#1857]
**Describe the bug**
Ops agent documentation here https://cloud.google.com/monitoring/agent/ops-agent/third-party/activemq advertises that ActiveMQ integration works with ActiveMQ Artemis 2.x brokers however it doesn't work. JMX metric keys have different format in Artemis so they are not returned to monitoring.

**To Reproduce**
1. Start a GCE VM with image 'rocky-linux-9-v20240515'
2. Install Ops Agent version 'google-cloud-ops-agent-2.52.0-1.el9.x86_64.rpm'
3. Install Artemis broker and enable JMX connector in management.xml
4. Customize the agent with configuration and restart the agent
```
metrics:
  receivers:
    activemq:
      type: activemq
      endpoint: localhost:1099
      collection_interval: 15s
      username: artemis
      password: artemis
  service:
    pipelines:
      activemq:
        receivers:
          - activemq

```
4. `netstat -an |grep LISTEN` shows that the agent connected to JMX management endpoint, but not metrics are gathered.

**Expected behavior**
ActiveMQ integration should work with ActiveMQ Artemis or documentation should be adjusted to remove Artemis from supported app list.

**Additional context**
Using JVM ops agent integration on the same Artemis installation works, so this is not the issue with Artemis or JMX configuration.
