### ISSUE TITLE
Exclude metrics feature not working as intended

### ISSUE THREAD

**Issue by mlazzje** [GoogleCloudPlatform/ops-agent#224]
I'm trying to exclude logging and some metrics to save money, by limiting the numbers of metrics ingested. See below my config:

```
logging:
  service:
    pipelines:
      default_pipeline:
        receivers: []
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern: 
        - agent.googleapis.com/agent/*
        - agent.googleapis.com/iis/*
        - agent.googleapis.com/interface/*
        - agent.googleapis.com/mssql/*
        - agent.googleapis.com/pagefile/*
        - agent.googleapis.com/swap/*
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
        processors: [metrics_filter]
```

Like this, nothing is excluded correctly, I can see everything in the metrics explorer. 
When I keep only " - agent.googleapis.com/agent/* ", it's working, I don't see agent metrics anymore, but if I replace with " - agent.googleapis.com/swap/* " I can still see swap metrics... I am restarting successfully the service every time.

Are there metrics not deactivatable? Or am I not writing the metrics correctly?

Windows Server 2019 Datacenter - using google-cloud-ops-agent.x86_64.2.3.1@1
