### ISSUE TITLE
GCP Ops Agent | Jvm Monitoring | Multiple process | Java | Single VM |

### ISSUE THREAD

**Issue by shivakumarss** [GoogleCloudPlatform/ops-agent#299]
I have GCP Ops Agent for JVM Monitoring in one of the VMs.

https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/third-party/jvm

This works fine with one jvm installed, I am able to see the data in gcp monitoring ui the data which is collected is shown in the UI.

The following configuration is used in `/etc/google-cloud-ops-agent/config.yaml`
```yml
metrics:
  receivers:
    jvm_metrics:
      type: jvm
      endpoint: localhost:9999
      collection_interval: 60s
  service:
    pipelines:
      jvm_pipeline:
        receivers:
          - jvm_metrics
```
          
I have a use case, there are 2 JVM processes running in a single machine, both are exposing the data in different jmx ports. Now how do I create a config in the .yml, such that I see data for both and I should be able to differentiate between these JVM metrics.

tried with different variations in the .yml file either get an invalid configuration error or the other jvm data doesn't show up in the gcp monitoring UI.

Any leads are highly appreciated.
