### ISSUE TITLE
Fedora CoreOS installation experiment

### ISSUE THREAD

**Issue by remoe** [GoogleCloudPlatform/ops-agent#334]
I tried to build and install ops-agent on the currently not supported Fedora CoreOS (https://getfedora.org/en/coreos https://docs.fedoraproject.org/en-US/fedora-coreos ). 

- Does one need special installation requirements for google-api to allow run this agent? 
- Does it only require the default GCP service-account? 
- Does have someone a solution idea for the systemd-services errors? 

Here are my log of this experiment:

# GCP VM OS

Fedora CoreOS 35.20220103.3.0

# ops-agent version

master: f516cab892283cf9a9092d693f600222c9785ce8

# Fedora 35 build commands:

```
FROM fedora:35 AS fedora35-build

RUN set -x; yum -y update && \
    dnf -y install 'dnf-command(config-manager)' && \
    yum -y install git systemd \
    autoconf libtool libcurl-devel libtool-ltdl-devel openssl-devel yajl-devel \
    gcc gcc-c++ make cmake bison flex file systemd-devel zlib-devel gtest-devel rpm-build systemd-rpm-macros \
    expect rpm-sign

ADD https://golang.org/dl/go1.17.linux-amd64.tar.gz /tmp/go1.17.linux-amd64.tar.gz
RUN set -xe; \
    tar -xf /tmp/go1.17.linux-amd64.tar.gz -C /usr/local

COPY . /work
WORKDIR /work
```

# RPM spec

https://github.com/GoogleCloudPlatform/ops-agent/blob/master/pkg/rpm/google-cloud-ops-agent.spec

# systemd services errors:

google-cloud-ops-agent:

```
The agent config file is not valid. Detailed error: failed to create directory for "conf/debug/built-in-config.yaml": mkdir conf: operation not permitted
```

google-cloud-ops-agent-opentelemetry-collector:

```
otelopscol[964]: application run finished with error: cannot build exporters: error creating googlecloud exporter: cannot configure Google Cloud metric exporter: stackdriver: no project found with application default credentials
otelopscol[964]: Error: cannot build exporters: error creating googlecloud exporter: cannot configure Google Cloud metric exporter: stackdriver: no project found with application default credentials
```
google-cloud-ops-agent-fluent-bit:

```
fluent-bit[929]: [error] [lib] backend failed
fluent-bit[929]: * https://fluentbit.io
fluent-bit[929]: * Fluent Bit is a CNCF sub-project under the umbrella of Fluentd
fluent-bit[929]: * Copyright (C) 2015-2018 Treasure Data
fluent-bit[929]: * Copyright (C) 2019-2021 The Fluent Bit Authors
fluent-bit[929]: Fluent Bit v1.8.11
```

# GCP VM Terraform resource

```
resource "google_compute_instance" "main" {
  name = var.instance_name
  zone         = var.zone
  machine_type = var.machine_type

  metadata = {
    user-data = data.ct_config.main-ignition.rendered
    ssh-keys = "[insert yours here]"
    serial-port-enable = "TRUE"
  }

  service_account {
    email  = "[insert yours here]"
    scopes = ["cloud-platform"]
  }

  boot_disk {
    auto_delete = true

    initialize_params {
      image = data.google_compute_image.fedora-coreos.self_link
      size  = var.disk_size
    }
  }

  network_interface {
    network = google_compute_network.network.name
  }

  can_ip_forward = true
  tags           = [var.instance_name, "http-server", "https-server"]

}
```

# Partial ignitionfile

```
variant: fcos
version: 1.2.0
storage:
  files:
    - path: /etc/google-cloud-ops-agent/config.yaml
      mode: 0600
      contents:
        inline: |
          logging:
            receivers:
              syslog:
                type: systemd_journald
            service:
              pipelines:
                default_pipeline:
                  receivers: [syslog]
          metrics:
            receivers:
              hostmetrics:
                type: hostmetrics
                collection_interval: 60s
            processors:
              metrics_filter:
                type: exclude_metrics
                metrics_pattern: []
            service:
              pipelines:
                default_pipeline:
                  receivers: [hostmetrics]
                  processors: [metrics_filter]

```
