### ISSUE TITLE
Some metrics cannot be excluded

### ISSUE THREAD

**Issue by mirkogrcic** [GoogleCloudPlatform/ops-agent#403]
Hello, we are using this config
```yaml

logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/messages
      - /var/log/syslog
  service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern:
      - agent.googleapis.com/cpu/*
      - agent.googleapis.com/interface/*
      - agent.googleapis.com/network/*
      - agent.googleapis.com/memory/bytes_used/*
      - agent.googleapis.com/swap/*
      - agent.googleapis.com/disk/io_time/*
      - agent.googleapis.com/disk/merged_operations/*
      - agent.googleapis.com/pagefile/*
      - agent.googleapis.com/disk/weighted_io_time/*
      - agent.googleapis.com/disk/write_bytes_count/*
      - agent.googleapis.com/disk/read_bytes_count/*
      - agent.googleapis.com/processes/*
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
        processors: [metrics_filter]
```

The `agent.googleapis.com/processes/*` exclusion and other ones with 2 path components (not including the `/*`) work but exclusions with 3 path components do not work (like `agent.googleapis.com/memory/bytes_used/*`)

Being excluded correctly:
- agent.googleapis.com/cpu/*
- agent.googleapis.com/interface/*
- agent.googleapis.com/network/*
- agent.googleapis.com/swap/*
- agent.googleapis.com/pagefile/*
- agent.googleapis.com/processes/*
      
Not being excluded:
- agent.googleapis.com/memory/bytes_used/*
- agent.googleapis.com/disk/io_time/*
- agent.googleapis.com/disk/merged_operations/*
- agent.googleapis.com/disk/weighted_io_time/*
- agent.googleapis.com/disk/write_bytes_count/*
- agent.googleapis.com/disk/read_bytes_count/*

I'm assuming the problem here is that metrics like `agent.googleapis.com/disk/read_bytes_count/*` do not branch out anymore so the ending `/*` is a problem because it expects it to branch out more, removing `/*` throws an error when starting the google-cloud-ops-agent as it's hardcoded to require it [here](https://github.com/GoogleCloudPlatform/ops-agent/blob/ecc3d139c9c1952bbd0dc4b97a921fcc4718a584/apps/metric_processors.go#L29)
Metrics like `agent.googleapis.com/processes/*` are getting excluded because they branch out into `agent.googleapis.com/processes/count_by_state` so the `/*` matches
