### ISSUE TITLE
Agent does not start when exclude_logs processor is used

### ISSUE THREAD

**Issue by vohtaski** [GoogleCloudPlatform/ops-agent#418]
We would like to filter out all syslog logs that are not relevant for our service.

We followed this guide and below is our configuration:
https://cloud.google.com/stackdriver/docs/solutions/agents/ops-agent/configuration#logging-processors

Process starts with this configuration
```
logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/syslog
  processors:
    parser_syslog:
      type: exclude_logs
      match_any: ['jsonPayload.message =~ "otelopscol"']
  service:
    pipelines:
      default_pipeline:
        receivers: []
      pipeline-syslog:
        receivers: [syslog]
        #processors: [parser_syslog]
```

However, whenever we uncomment this line "processors: [parser_syslog]", the process fails to start.
```
logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/syslog
  processors:
    parser_syslog:
      type: exclude_logs
      match_any: ['jsonPayload.message =~ "otelopscol"']
  service:
    pipelines:
      default_pipeline:
        receivers: []
      pipeline-syslog:
        receivers: [syslog]
        processors: [parser_syslog]
```

Not sure what is wrong.

![image (10)](https://user-images.githubusercontent.com/158421/154527149-5274aaed-70cb-4278-b699-05336dcc77fe.png)

Version of Agent:
```
nginx:~$ dpkg-query --show --showformat \
    '${Package} ${Version} ${Architecture} ${Status}\n' \
     google-cloud-ops-agent
google-cloud-ops-agent 2.10.0~ubuntu20.04 amd64 install ok installed
```
