### ISSUE TITLE
Couldn't set log file full path as receiver ID

### ISSUE THREAD

**Issue by QI-D** [GoogleCloudPlatform/ops-agent#448]
I was trying to set a log file full path "/var/log/abc.log" as receiver ID in the config.ymal, then I got this following error:
`[2022/03/03 22:57:39] [ warn] [output:stackdriver:stackdriver.0] error
{
  "error": {
    "code": 400,
    "message": "Received unexpected value parsing name \"projects/qd-mar3/logs//var/log/abc.log\": abc.log. Expected the form projects/[PROJECT_ID]/logs/[ID]",
    "status": "INVALID_ARGUMENT"
  }
}`. 
AWS CloudWatch Agent allows users to set file full path as the log stream name/ log name. I'm wondering if users can set log file full path as log name/ receiver ID with Ops Agent.

**Comment by yfuruyama** [comment]
Hi @QI-D I'm not sure if I understand your intention, but if your intention is sending the logs of `/var/log/abc.log` to Cloud Logging, you can write the following config.
```
logging:
  receivers:
    abc:
      type: files
      include_paths:
        - /var/log/abc.log
  service:
    pipelines:
      abc:
        receivers:
          - abc
```
