### ISSUE TITLE
Add support for httpRequest field for JSON playload

### ISSUE THREAD

**Issue by nonokangwei** [GoogleCloudPlatform/ops-agent#460]
When JSON payload include httpRequest field, it can be mapping to httpRequest field in LogEntry.

**Comment by zbjornson** [comment]
It seems like `jsonPayload.httpRequest` should just work. Is this the best workaround?

```yaml
    http_response:
      type: modify_fields
      fields:
        httpRequest.requestMethod:
          move_from: jsonPayload.httpRequest.requestMethod
        httpRequest.requestUrl:
          move_from: jsonPayload.httpRequest.requestUrl
        httpRequest.requestSize:
          move_from: jsonPayload.httpRequest.requestSize
        httpRequest.status:
          move_from: jsonPayload.httpRequest.status
        httpRequest.responseSize:
          move_from: jsonPayload.httpRequest.responseSize
        httpRequest.userAgent:
          move_from: jsonPayload.httpRequest.userAgent
        httpRequest.remoteIp:
          move_from: jsonPayload.httpRequest.remoteIp
        httpRequest.referer:
          move_from: jsonPayload.httpRequest.referer
        httpRequest.latency:
          move_from: jsonPayload.httpRequest.latency
```

The docs also incorrectly document `httpRequest` as a string field instead of an [`HttpRequest`](https://cloud.google.com/logging/docs/reference/v2/rest/v2/LogEntry#HttpRequest): https://cloud.google.com/logging/docs/agent/ops-agent/configuration#special-fields
