### ISSUE TITLE
JSON Parser removes existing fields

### ISSUE THREAD

**Issue by stevenkissack** [GoogleCloudPlatform/ops-agent#650]
**Describe the bug**
When chaining a parse_regex and parse_json processor, the json result will replace the fields parsed by the parse_regex

**To Reproduce**
1. Log a message with partial json, e.g. syslog with json message content
2. Capture with Ops Agent (I'm using 2.13 but see no change in the docs)
3. Customize the agent with configuration below to create the basic pipeline
4. See that fields of the first processor wipes the second, likely due to it not staying as a child field

**Expected behavior**
That the conversion of message json would keep existing fields or allow the user to specify to keep the json in a nested field.

**Environment (please complete the following information):**
 - Project ID: not required?
 - VM ID : not required?
 - VM distro / OS: Debian Bullseye
 - Ops Agent version: 2.13
 - Ops Agent configuration (below)
 - Ops Agent log: normal start

**Additional context**
Config:
```
logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/messages
      - /var/log/syslog
  processors:
    parse_syslog:
      type: parse_regex
      regex: "/^(?<time>[^ ]* {1,2}[^ ]* [^ ]*) (?<host>[^ ]*) (?<ident>[a-zA-Z0-9_\/\.\-]*)(?:\[(?<pid>[0-9]+)\]>
      time_key:    time
      time_format: %b %d %H:%M:%S
    json_message:
      type: parse_json
      field: message
  service:
    pipelines:
      default_pipeline:
        receivers: [syslog]
        processors: [parse_syslog,json_message]
```

Before any processing we see the standard syslog format:

```
"jsonPayload": {
    "message": "Jun  4 12:57:57 staging-server docker.caddy-1[589]: {"level":"info" ....}"
 }
```

Result of one log from our caddy proxy container when using just the parse_syslog processor (chose something not sensitive):

```
{
  "insertId": "1iocguefacpy3j",
  "jsonPayload": {
    "message": "{\"level\":\"error\",\"ts\":1654359293.8545134,\"logger\":\"http.log.access.log0\",\"msg\":\"handled request\",\"request\":{\"remote_addr\":\"89.104.111.10:38577\",\"proto\":\"HTTP/1.1\",\"method\":\"GET\",\"host\":\"staging.website.co.uk\",\"uri\":\"/favicon.ico\",\"headers\":{\"User-Agent\":[\"Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/94.0.4606.61 Safari/537.36\"],\"Accept\":[\"*/*\"],\"Accept-Encoding\":[\"gzip, deflate\"]},\"tls\":{\"resumed\":false,\"version\":772,\"cipher_suite\":4865,\"proto\":\"\",\"proto_mutual\":true,\"server_name\":\"staging.website.co.uk\"}},\"common_log\":\"89.104.111.10 - - [04/Jun/2022:16:14:53 +0000] \\\"GET /favicon.ico HTTP/1.1\\\" 404 150\",\"duration\":0.002434131,\"size\":150,\"status\":404,\"resp_headers\":{\"Content-Length\":[\"150\"],\"Strict-Transport-Security\":[\"max-age=31536000;\"],\"X-Xss-Protection\":[\"1; mode=block;\"],\"X-Robots-Tag\":[\"none;\"],\"Content-Security-Policy\":[\"default-src 'none'\"],\"X-Content-Type-Options\":[\"nosniff;\"],\"Content-Type\":[\"text/html; charset=utf-8\"],\"Date\":[\"Sat, 04 Jun 2022 13:14:50 GMT\"],\"Referrer-Policy\":[\"no-referrer;\"],\"X-Frame-Options\":[\"SAMEORIGIN;\"]}}",
    "host": "staging",
    "pid": "589",
    "ident": "docker.caddy-1"
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "zone": "europe-xx-x",
      "instance_id": "0000000",
      "project_id": "xxxx"
    }
  },
  "timestamp": "2022-06-04T16:14:53Z",
  "logName": "projects/xxxx/logs/syslog",
  "receiveTimestamp": "2022-06-04T16:14:54.298112604Z"
}
```

You can see we've now got the correct structure, just need to convert the message field to json with a possible rename

Result after then parsing the json message field (different log but issue is clear):

```
{
  "insertId": "18ebqwlfbxq5hf",
  "jsonPayload": {
    "size": 159,
    "ts": 1644362311.272316,
    "resp_headers": {
      "Content-Type": [
        "text/html; charset=utf-8"
      ],
      "Date": [
        "Sat, 04 Jun 2022 13:05:20 GMT"
      ]
    },
    "logger": "http.log.access.log0",
    "user_id": "",
    "msg": "handled request",
    "common_log": "xxx.xx.xxx.xx - - [04/Jun/2022:13:05:20 +0000] \"GET /apple-touch-icon.png HTTP/2.0\" 404 159",
    "request": {
      "headers": {
        "Accept-Encoding": [
          "gzip, deflate, br"
        ]
      },
      "method": "GET",
      "host": "staging.website.co.uk",
      "tls": {
        "proto": "h2"
      },
      "uri": "/apple-touch-icon.png",
      "remote_addr": "xxx.xxxx:xxx",
      "proto": "HTTP/2.0"
    },
    "level": "error",
    "duration": 0.00206551,
    "status": 404
  },
  "resource": {
    "type": "gce_instance",
    "labels": {
      "instance_id": "000000",
      "zone": "europe-XX-x",
      "project_id": "XXXXXX"
    }
  },
  "timestamp": "2022-06-03T14:05:21Z",
  "logName": "projects/xxxxx/logs/syslog",
  "receiveTimestamp": "2022-06-04T17:05:21.298848571Z"
}
```

You'll notice we lost pid, host & ident form the original jsonPayload object.

I appreciate this might not be standard behaviour, but I can't seem to figure out how to use the underlying fluentbit nest plugin to try and help, and as the product grows I can see this being a very standard feature.. or I'm missing something

Possible definitions to not break existing functionality:
```
json_message:
      type: parse_json
      field: message
      preserve_data: true

json_message:
      type: parse_json
      field: message
      output: jsonPayload.message
```

Related SO post from somebody else: https://stackoverflow.com/questions/69464741/how-to-pipe-processing-fields-by-regex-and-json-in-google-ops-agent

Any help is appreciated!

**Comment by jefferbrecht** [comment]
Hi @stevenkissack & @jokester; fields are now preserved by default when parsing JSON.

The original example given in the issue should now work as expected without dropping `pid`, `host` and `ident`.

@jokester's example can be parsed with chained JSON parsers:

```yaml
logging:
  receivers: ...
  processors:
    json1:
      type: parse_json
    json2:
      type: parse_json
      field: log
  service:
    pipelines:
      docker:
        receivers: [ ... ]
        processors: [ json1, json2 ]
```

So a log that looks like this in the file:

```json
{"container_id": "12345678", "log": "{\"field1\": \"...\"}"}
```

Will end up looking like this:

```json
{
  "container_id": "12345678",
  "field1": "..."
}
```

We'll close this issue now as it appears to be resolved, but please feel free to re-open it if you have further questions!
