### ISSUE TITLE
Not able to get IIS Logs

### ISSUE THREAD

**Issue by chetan-ha** [GoogleCloudPlatform/ops-agent#720]
Not able to get `IIS Logs`.

OS Version: Windows Server 2012 R2
Ops Agent Version: 2.17.0

Config File - [Reference Link](https://cloud.google.com/monitoring/agent/ops-agent/third-party/iis)
```
logging:
  receivers:
    windows_event_log:
      type: windows_event_log
      channels: [System, Application, Security]
    iis_access:
      type: iis_access
      include_paths:
        - "C:\\inetpub\\logs\\LogFiles\\W3SVC1\\uex*"
        - "C:\\inetpub\\logs\\LogFiles\\W3SVC2\\uex*"
        - "C:\\inetpub\\logs\\LogFiles\\W3SVC3\\uex*"
        - "C:\\inetpub\\logs\\LogFiles\\W3SVC4\\uex*"
  service:
    pipelines:
      default_pipeline:
        receivers: [windows_event_log]
      iis:
        receivers: [iis_access]
metrics:
  receivers:
    hostmetrics:
      type: hostmetrics
      collection_interval: 60s
    iis_v2:
      type: iis
      receiver_version: 2
  processors:
    metrics_filter:
      type: exclude_metrics
      metrics_pattern: []
  service:
    pipelines:
      default_pipeline:
        receivers: [hostmetrics]
        processors: [metrics_filter]
      iispipeline:
        receivers: [iis_v2]
```
This do not throw any error, nothing suspicious in `logging-module.log` as well.
Tried some custom application logs with regex defined, it worked well. 
Additional Information: This is an existing server, which do have `IIS` running since long time with old logs kept intact.
