### ISSUE TITLE
lastest version installed but console calls it "legacy"

### ISSUE THREAD

**Issue by black-snow** [GoogleCloudPlatform/ops-agent#737]
NOTE: This might not belong here / might be an issue with the console webapp.

**Describe the bug**
GCP VM dashboard reports VM as having legacy log agents installed, which is just not true. It has the latest (`google-cloud-ops-agent 2.18.1~debian10 amd64 install ok installed`) version and had never neither the old logging nor metrics agent installed. I double-checked and restarted it several times.

![grafik](https://user-images.githubusercontent.com/579733/179546683-979a974c-6253-4752-90ef-9cad5df3efff.png)

This happens for some VMs only. Others work just fine and they are essentially pretty much all the same (maybe different java versions installed but that's about it).

**To Reproduce**
1. Start a GCE VM with Debian 10
2. Install Ops Agent version *latest*
3. See error, hopefully, for some but not all VMs

**Expected behavior**
Monitoring displays "Ops Agent" with a green checkmark.

**Environment (please complete the following information):**
 - Project ID dtad-prod-monitoring
 - VM ID prod-fuv-service-vm 
 - VM distro / OS: Debian 10
 - Ops Agent version 2.18.1
 - Ops Agent configuration:
 
```yaml
logging:
  receivers:
    xyz:
      type: files
      include_paths:
      - /opt/zyx/xyz/log/some.log
  service:
    pipelines:
      xyz_pipeline:
        receivers: [xyz]
```
