### ISSUE TITLE
Use systemd_journald receiver by default on Linux

### ISSUE THREAD

**Issue by jeremyvisser** [GoogleCloudPlatform/ops-agent#822]
Since Ops Agent effectively only ships with systemd support on Linux, I think it makes sense to change to using the `systemd_journald` receiver by default instead of the `files` receiver.

The deb/rpm packages only ship with systemd unit files, not sysvinit scripts. RHEL 7+ requires systemd, Debian Jessie and above have started to remove sysvinit scripts from packages. It's a reasonable expectation that ~everyone using Ops Agent on Linux will be doing so on systemd with journald.

Using the systemd_journald receiver gives significantly richer log fields, which makes filtering and searching in Cloud Logging much more convenient.

So I propose this part of the default config from...

```
logging:
  receivers:
    syslog:
      type: files
      include_paths:
      - /var/log/messages
      - /var/log/syslog
```

...to:

```
logging:
  receivers:
    syslog:
      type: systemd_journald
```
