### ISSUE TITLE
Missing data points with monitoring metric `log_entry_count` and `request_count`

### ISSUE THREAD

**Issue by PierreBart** [GoogleCloudPlatform/ops-agent#877]
**Describe the bug**

In Cloud Monitoring, the values of the metrics `agent.googleapis.com/agent/log_entry_count` and `agent.googleapis.com/agent/request_count` do not increase even though the Logging Agent keeps sending logs to Cloud Logging.

Also, by querying the `/metrics` path of the fluent bit agent on an instance, I can see that the metric `fluentbit_stackdriver_proc_records_total` keeps increasing.

Other metrics such as `uptime` or `memory_usage` seem fine and report legit values.

**Expected behavior**

The `log_entry_count` and `request_count` metrics increase as logs are forwarded to Cloud Logging by the Logging Agent.

**Environment:**
 - VM distro / OS:  Debian 10
 - Ops Agent version: 2.21.0
 - Ops Agent configuration:
 ```yaml
logging:
  processors:
    docker:
      time_format: '%Y-%m-%dT%H:%M:%S.%LZ'
      time_key: time
      type: parse_json
    syslog:
      regex: '^\S+ \d+ \d+:\d+:\d+ (?<vm_name>\S+) (?<process>\S+)\[\d+\]: (?<message>.*)$'
      type: parse_regex
  receivers:
    docker:
      include_paths:
      - /var/lib/docker/containers/*/*-json.log
      type: files
    syslog:
      include_paths:
      - /var/log/messages
      - /var/log/syslog
      type: files
  service:
    pipelines:
      default_pipeline:
        processors:
        - syslog
        receivers:
        - syslog
      docker:
        processors:
        - docker
        receivers:
        - docker
metrics:
  service:
    pipelines:
      default_pipeline:
        receivers: []
 ```

**Additional information**

The Ops Agent is installed with the Ansible playbook https://github.com/GoogleCloudPlatform/google-cloud-ops-agents-ansible.
